/*!50503 SET NAMES utf8mb4 */;

CREATE USER 'nacos'@'%' IDENTIFIED BY '#{MYSQL_NACOS_PASSWORD}';
GRANT ALL PRIVILEGES ON `uw_nacos`.* TO 'nacos'@'%';
FLUSH PRIVILEGES;

CREATE USER 'uw'@'%' IDENTIFIED BY '#{MYSQL_UW_PASSWORD}';
GRANT ALL PRIVILEGES ON `uw_%`.* TO 'uw'@'%';
FLUSH PRIVILEGES;

CREATE USER 'saas'@'%' IDENTIFIED BY '#{MYSQL_SAAS_PASSWORD}';
GRANT ALL PRIVILEGES ON `saas_%`.* TO 'saas'@'%';
FLUSH PRIVILEGES;
