server.port=8848
server.servlet.contextPath=/nacos

spring.sql.init.platform=mysql
db.num=1
db.url.0=jdbc:mysql://#{MYSQL_HOST}:#{MYSQL_PORT}/uw_nacos?characterEncoding=utf8&connectTimeout=3000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.user.0=nacos
db.password.0=#{MYSQL_NACOS_PASSWORD}

### Connection pool config
db.pool.config.connectionTimeout=30000
db.pool.config.validationTimeout=10000
db.pool.config.maximumPoolSize=100
db.pool.config.minimumIdle=3

### The auth system to use, currently only 'nacos' and 'ldap' is supported:
nacos.core.auth.system.type=nacos

### If turn on auth system:
nacos.core.auth.enabled=true
nacos.core.auth.caching.enabled=true
nacos.core.auth.server.identity.key=#{NACOS_IDENTITY_KEY}
nacos.core.auth.server.identity.value=#{NACOS_IDENTITY_VALUE}
nacos.core.auth.plugin.nacos.token.secret.key=#{NACOS_TOKEN_KEY}
nacos.core.auth.plugin.nacos.token.expire.seconds=18000