# network
port 6380
tcp-backlog 511
timeout 0
tcp-keepalive 300
# database
databases 128
requirepass #{REDIS_PASSWORD}
maxclients 100000
# memory
maxmemory-policy volatile-lru
maxmemory 32gb
# aof&rdb
rdbcompression yes
appendonly yes
appendfilename "appendonly.aof"
appendfsync no
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 256mb
aof-load-truncated yes
aof-use-rdb-preamble yes
# lua
lua-time-limit 10000
# slowlog
slowlog-log-slower-than 10000
slowlog-max-len 128
